name: CORE_Day3

channels:
  # Conda forge - gives us lots of community-built Python packages, see https://conda-forge.org/ for details
  - conda-forge

dependencies:
  - numpy
  - pandas
  - matplotlib
  - seaborn>=0.9
  - scikit-learn
  - jupyter
